### ISSUE TITLE
Data Access Interfaces

### ISSUE THREAD

**Issue by lucasprates74** [CSC207-2022F-UofT/course-project-team-bbq#11]

**Comment by uoftguy** [comment]
For the CommonUserDataAccess are there any classes for getPassword or getFlashcardSetIds methods that allow for Login to utilize them while logging in a player and for the UserLoginResponseModel?

**Comment by ThomasShimUoft** [comment]
If you have the username you can get both password and flashcardSetIds. You can get a commonUserDsRequestModel from the CommonUserDataAccess and in commonUserDsRequestModel we have getters for password and flashcardSetIds. So if in your situation you have access to a username then you don't need to worry. If not then we might have to add a few methods.
What do you need this for?

**Comment by winstonc03** [comment]
CommonUserDataAccess is missing the "isAdmin" attribute in the headers in the current version so it wasn't able to parse through the users csv when I was running my program, I can add it in my version when I push to main if it hasn't been done already.
