### ISSUE TITLE
[Feature 8] Searching for Community Flashcards

### ISSUE THREAD

**Issue by winstonc03** [CSC207-2022F-UofT/course-project-team-bbq#3]
Allow Users to search using tags and keywords for Flashcard sets within the community database. Only public flashcard sets will be returned to CommonUsers, while admins will be able to see all flashcardSets. All relevant flashcardSets will be returned to the user and they can select a Set to begin studying or test themselves on.

**Comment by lucasprates74** [comment]
just wanted to leave comment saying, for your use case, an admin user should be able to search the entire database, not just the public flashcard sets

**Comment by winstonc03** [comment]
Ok sounds good, I'll have the interactor check the isAdmin attribute as well to ignore the private attribute so it can add the private flashcardSets.
