### ISSUE TITLE
Fix saveFlashcard and saveFlashcardSet Methods in FlashcardDataAccess, FlashcardSetDataAccess

### ISSUE THREAD

**Issue by ThomasShimUoft** [CSC207-2022F-UofT/course-project-team-bbq#37]
Fix saveFlashcard and saveFlashcardSet Methods in FlashcardDataAccess, FlashcardSetDataAccess

**Comment by Junyu11111** [comment]
setFlashcardId has not been added to saveFlashcard in FlashcardDataAccess.

**Comment by ThomasShimUoft** [comment]
Added it to the wrong method. I'll change it right now.
