### ISSUE TITLE
FlashcardSetDataAccess warning

### ISSUE THREAD

**Issue by Edward-1117** [CSC207-2022F-UofT/course-project-team-bbq#41]
https://github.com/CSC207-2022F-UofT/course-project-team-bbq/blob/a8f562c191d6fd417fb393a64a20fbf1b9dc663f/src/main/java/dataAccess/FlashcardSetDataAccess.java#L64

The string format method is giving a warning about there being 6 arguments but only 5 "%s". Is this intentional?

**Comment by ThomasShimUoft** [comment]
Yeah I think if you see in the next line there is another argument, set.getFlashcardIds(). This argument is not supposed to be there, we should fix this.

**Comment by jempio** [comment]
Was this fixed?

**Comment by jempio** [comment]
Okay we are good!
