### ISSUE TITLE
[Feature 3] Creating a Flashcard Set

### ISSUE THREAD

**Issue by Edward-1117** [CSC207-2022F-UofT/course-project-team-bbq#6]
Allow users to create either public or private flashcard sets.

**Comment by lucasprates74** [comment]
you should give a new flashcard set a placeholder id like "-1". Justin's database will take care of storing it with a unique id for later use.

**Comment by Edward-1117** [comment]
Oh okay, so does that mean I can get rid of the counter attribute?

**Comment by ThomasShimUoft** [comment]
What counter attribute are you referring to? In which class is this in?

From my knowledge when you create a new flashcard set you should manually set the FlashcardSetId as "-1" when you construct the FlashcardSetDSRequestModel. Then the database classes will handle the id portion of the flashcardSet.

**Comment by ThomasShimUoft** [comment]
> What counter attribute are you referring to? In which class is this in?
> 
> From my knowledge when you create a new flashcard set you should manually set the FlashcardSetId as "-1" when you construct the FlashcardSetDSRequestModel. Then the database classes will handle the id portion of the flashcardSet.

What counter attribute are you referring to? In which class is this in?

From my knowledge when you create a new flashcard set you should manually set the FlashcardSetId as "-1" when you construct the FlashcardSetDSRequestModel. Then the database classes will handle the id portion of the flashcardSet.

**Comment by Edward-1117** [comment]
I initially had a static counter for flashcard set ids in my interactor class prior to working with Justin's database. I already got rid of that attribute to work with the database, so sorry for the confusion!
