### ISSUE TITLE
(Bug) Register Screen Disposal

### ISSUE THREAD

**Issue by anthony-chen-ca** [CSC207-2022F-UofT/course-project-team-bbq#64]
After registering using the register screen, my home page screen pops up. However, the register screen still remains on my screen. We should probably dispose of it once a new user has signed up.

**Comment by uoftguy** [comment]
Yeah, the thing is previously when I disposed it for some reason the screen would get disposed even after some input errors. So there needs to be a way that the screen stays up even if there are failure views presented, but closes once the user registers.

**Comment by uoftguy** [comment]
Fixed the bug in Pull Request #79
