### ISSUE TITLE
[Feature 5] Add Flashcard to Flashcard Set​

### ISSUE THREAD

**Issue by Junyu11111** [CSC207-2022F-UofT/course-project-team-bbq#7]
Add Flashcard to Flashcard Set​

**Comment by lucasprates74** [comment]
you should give a new flashcard a placeholder id like "-1". Justin's database will take care of storing it with a unique id for later use.

**Comment by lucasprates74** [comment]
you should give a new flashcard set a placeholder id like "-1". Justin's database will take care of storing it with a unique id for later use.

**Comment by ThomasShimUoft** [comment]
If we do what Lucas is saying, then I think it might be appropriate to make a setter function in the requestModel class. It is either this or we must create a new requestModel in the dataAccess classes and copy in the old request model information to the new, which can seem a little tedious.

Let's get Justin's opinion on this.

**Comment by ThomasShimUoft** [comment]
I think your create flashcard should be using the DBGateway instead of the separate dataAccess classes in your interactor class. Right now we get a warning message saying that saveFlashcard method in DBGateway is not being used.
